### PR TITLE
Add .htaccess do documentation

### PR DESCRIPTION
**Pull request by malukenho**

### CODE REVIEW

**Comment by LeJeanbono** [comment]
.htaccess to discard rules for js / css inclusion :
Options +FollowSymLinks
RewriteEngine On
RewriteRule ^(js|css)($|/) - [L]
RewriteRule ^(.*)$ index.php [NC,L]

**Comment by malukenho** [comment]
@LeJeanbono previous code has problem with css/img/js or so kind of file?

**Comment by LeJeanbono** [comment]
Nope, that's good
I just don't want to write routes for path like : <script src='js/bootstrap-typeahead.js'></script>
Thanks for your lib ;)

**Comment by malukenho** [comment]
@LeJeanbono you're welcome :)
Thank you for use `PHP Router`

**Pull request merged**
