### PR TITLE
Fix issue #110

### PR DESCRIPTION
**Pull request by antoine-pous**
This fix implement implement strict filters names, now they should contains only letters and start with `:`. If don't PHPRouter throw an exception.

### CODE REVIEW

**Comment by malukenho** [comment]
@antoine-pous no tests added? =X

**Comment by antoine-pous** [comment]
currently i can't made units tests, phpunit for PHPRouter is really outdated :(

**Comment by malukenho** [comment]
Still need tests to prevent regression. It doesn't matter if phpunit is outdated or not IMO

**Comment by antoine-pous** [comment]
I'll update them ASAP

**Pull request merged**
