### PR TITLE
Fix psr 0

### PR DESCRIPTION
**Pull request by jarednova**
Currently the composer.json file has the `psr-0` name as `PHProuter` -- it should be `PHPRouter`

### CODE REVIEW

**Comment by malukenho** [comment]
@jarednova please, rebase your PR :}

**Comment by jarednova** [comment]
@malukenho I'm a little stuck here. I _think_ there's some disagreement between the [`1.0` branch](https://github.com/dannyvankooten/PHP-Router/tree/1.0) and the [`1.0.0-alpha` release](https://github.com/dannyvankooten/PHP-Router/releases/tag/1.0.0-alpha). Basically I want to update the 1.0.0 alpha release as seen here:

https://github.com/jarednova/PHP-Router/compare/dannyvankooten:1.0.0-alpha...fix_psr_0

... but (at least from this view) I can't create a pull request b/c there isn't a branch. What is the best way to proceed? Could you create a fresh branch from `1.0.0-alpha` so that I can create a PR on it? Then this could potentially be released as `1.0.1-alpha` or `1.0.0-beta`.

**Comment by malukenho** [comment]
@jarednova yah! The `1.0` current branch is a very old version of PHPRouter. I will fix that today and ping you here. Anyway, we don't need maintain that old version.

**Comment by malukenho** [comment]
@jarednova I change the name of branch, feel free to send your PR again. Thanks!

**Pull request closed without merging**
