### PR TITLE
comoser: allow PHP 7 in safer way

### PR DESCRIPTION
**Pull request by TomasVotruba**

### CODE REVIEW

**Comment by TomasVotruba** [comment]
What needs to be done here?

**Comment by antoine-pous** [comment]
Nothing, just merge.

I don't understand why we are still waiting for it :/

**Comment by TomasVotruba** [comment]
Awesome :)

**Comment by malukenho** [comment]
@antoine-pous still we don't have CI. Please don't just merge stuff around.

**Comment by TomasVotruba** [comment]
@malukenho What is the blocker for CI?

**Pull request merged**
